### ISSUE TITLE
feature: 对于用户登录失败，前端应该弹出窗口提醒

### ISSUE THREAD

**Issue by wiketool** [SDU-Open-Project/issues#1]
登陆所使用的用户名：-1
登录所使用的密码：1243

**Comment by Criheacy** [comment]
登录失败时前端确实会显示一条错误提示，类似下图：

![image](https://user-images.githubusercontent.com/53986940/223307081-b3a5439c-8591-48f1-bee1-53473c078e2c.png)

现在因为线上版本服务端不稳定，前端有时收不到正确结果，请等待下个版本更新（将在几天后上线）再测试。

如果对当前提示框的样式不满意，请重新开启此 issue。
